// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: ghoststate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional fixed read-only adoption evidence; ordinary state reads stay lightweight.
	IncludeAdoptionEvidence bool `protobuf:"varint,1,opt,name=include_adoption_evidence,json=includeAdoptionEvidence,proto3" json:"include_adoption_evidence,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_ghoststate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghoststate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_ghoststate_proto_rawDescGZIP(), []int{0}
}

func (x *GetStateRequest) GetIncludeAdoptionEvidence() bool {
	if x != nil {
		return x.IncludeAdoptionEvidence
	}
	return false
}

// State is deliberately a thin envelope around raw, structured JSON per
// domain rather than a typed nftables/netconfig schema in proto itself:
// each domain's real shape is still being designed (Phase 4/5), and the
// envelope is what lets GetState/Apply exist now without churning the
// wire format every time a domain's internals change.
type State struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `nft -j list ruleset` output, verbatim.
	NftRulesetJson string `protobuf:"bytes,1,opt,name=nft_ruleset_json,json=nftRulesetJson,proto3" json:"nft_ruleset_json,omitempty"`
	// machines.net_ifaces's own live-read shape (persisted interfaces.d file
	// bytes + `ip -j addr show` + /proc/sys/net/ipv4/ip_forward), as JSON.
	NetconfigJson        string `protobuf:"bytes,2,opt,name=netconfig_json,json=netconfigJson,proto3" json:"netconfig_json,omitempty"`
	AdoptionEvidenceJson string `protobuf:"bytes,3,opt,name=adoption_evidence_json,json=adoptionEvidenceJson,proto3" json:"adoption_evidence_json,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_ghoststate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_ghoststate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_ghoststate_proto_rawDescGZIP(), []int{1}
}

func (x *State) GetNftRulesetJson() string {
	if x != nil {
		return x.NftRulesetJson
	}
	return ""
}

func (x *State) GetNetconfigJson() string {
	if x != nil {
		return x.NetconfigJson
	}
	return ""
}

func (x *State) GetAdoptionEvidenceJson() string {
	if x != nil {
		return x.AdoptionEvidenceJson
	}
	return ""
}

type ApplyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The fully-resolved declarative target Nornir computed — not a diff.
	DesiredStateJson string `protobuf:"bytes,1,opt,name=desired_state_json,json=desiredStateJson,proto3" json:"desired_state_json,omitempty"`
	// How long the dead-man's-switch waits for Confirm before reverting to
	// the pre-apply snapshot. Required; the caller does not get to apply
	// with no revert path.
	DeadManSwitchSeconds int32 `protobuf:"varint,2,opt,name=dead_man_switch_seconds,json=deadManSwitchSeconds,proto3" json:"dead_man_switch_seconds,omitempty"`
	// Which domain desired_state_json is for: "firewall" or "netconfig".
	// Required — the two domains' desired_state_json shapes are incompatible,
	// and routing one to the wrong renderer on a guess is not a survivable
	// mistake to auto-detect.
	Domain        string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_ghoststate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghoststate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_ghoststate_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyRequest) GetDesiredStateJson() string {
	if x != nil {
		return x.DesiredStateJson
	}
	return ""
}

func (x *ApplyRequest) GetDeadManSwitchSeconds() int32 {
	if x != nil {
		return x.DeadManSwitchSeconds
	}
	return 0
}

func (x *ApplyRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_ghoststate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ghoststate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_ghoststate_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type ConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_ghoststate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghoststate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_ghoststate_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type ConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmResponse) Reset() {
	*x = ConfirmResponse{}
	mi := &file_ghoststate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmResponse) ProtoMessage() {}

func (x *ConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ghoststate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmResponse.ProtoReflect.Descriptor instead.
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return file_ghoststate_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_ghoststate_proto protoreflect.FileDescriptor

const file_ghoststate_proto_rawDesc = "" +
	"\n" +
	"\x10ghoststate.proto\x12\x06ghostd\"M\n" +
	"\x0fGetStateRequest\x12:\n" +
	"\x19include_adoption_evidence\x18\x01 \x01(\bR\x17includeAdoptionEvidence\"\x8e\x01\n" +
	"\x05State\x12(\n" +
	"\x10nft_ruleset_json\x18\x01 \x01(\tR\x0enftRulesetJson\x12%\n" +
	"\x0enetconfig_json\x18\x02 \x01(\tR\rnetconfigJson\x124\n" +
	"\x16adoption_evidence_json\x18\x03 \x01(\tR\x14adoptionEvidenceJson\"\x8b\x01\n" +
	"\fApplyRequest\x12,\n" +
	"\x12desired_state_json\x18\x01 \x01(\tR\x10desiredStateJson\x125\n" +
	"\x17dead_man_switch_seconds\x18\x02 \x01(\x05R\x14deadManSwitchSeconds\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\"*\n" +
	"\rApplyResponse\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"+\n" +
	"\x0eConfirmRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"!\n" +
	"\x0fConfirmResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xb1\x01\n" +
	"\tHostState\x122\n" +
	"\bGetState\x12\x17.ghostd.GetStateRequest\x1a\r.ghostd.State\x124\n" +
	"\x05Apply\x12\x14.ghostd.ApplyRequest\x1a\x15.ghostd.ApplyResponse\x12:\n" +
	"\aConfirm\x12\x16.ghostd.ConfirmRequest\x1a\x17.ghostd.ConfirmResponseB\x18Z\x16smarthome/ghostd/protob\x06proto3"

var (
	file_ghoststate_proto_rawDescOnce sync.Once
	file_ghoststate_proto_rawDescData []byte
)

func file_ghoststate_proto_rawDescGZIP() []byte {
	file_ghoststate_proto_rawDescOnce.Do(func() {
		file_ghoststate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ghoststate_proto_rawDesc), len(file_ghoststate_proto_rawDesc)))
	})
	return file_ghoststate_proto_rawDescData
}

var file_ghoststate_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ghoststate_proto_goTypes = []any{
	(*GetStateRequest)(nil), // 0: ghostd.GetStateRequest
	(*State)(nil),           // 1: ghostd.State
	(*ApplyRequest)(nil),    // 2: ghostd.ApplyRequest
	(*ApplyResponse)(nil),   // 3: ghostd.ApplyResponse
	(*ConfirmRequest)(nil),  // 4: ghostd.ConfirmRequest
	(*ConfirmResponse)(nil), // 5: ghostd.ConfirmResponse
}
var file_ghoststate_proto_depIdxs = []int32{
	0, // 0: ghostd.HostState.GetState:input_type -> ghostd.GetStateRequest
	2, // 1: ghostd.HostState.Apply:input_type -> ghostd.ApplyRequest
	4, // 2: ghostd.HostState.Confirm:input_type -> ghostd.ConfirmRequest
	1, // 3: ghostd.HostState.GetState:output_type -> ghostd.State
	3, // 4: ghostd.HostState.Apply:output_type -> ghostd.ApplyResponse
	5, // 5: ghostd.HostState.Confirm:output_type -> ghostd.ConfirmResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ghoststate_proto_init() }
func file_ghoststate_proto_init() {
	if File_ghoststate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ghoststate_proto_rawDesc), len(file_ghoststate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ghoststate_proto_goTypes,
		DependencyIndexes: file_ghoststate_proto_depIdxs,
		MessageInfos:      file_ghoststate_proto_msgTypes,
	}.Build()
	File_ghoststate_proto = out.File
	file_ghoststate_proto_goTypes = nil
	file_ghoststate_proto_depIdxs = nil
}
