// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: ghoststate.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostState_GetState_FullMethodName       = "/ghostd.HostState/GetState"
	HostState_Apply_FullMethodName          = "/ghostd.HostState/Apply"
	HostState_Confirm_FullMethodName        = "/ghostd.HostState/Confirm"
	HostState_GetRegistry_FullMethodName    = "/ghostd.HostState/GetRegistry"
	HostState_ImportLeases_FullMethodName   = "/ghostd.HostState/ImportLeases"
	HostState_ReportHost_FullMethodName     = "/ghostd.HostState/ReportHost"
	HostState_RepairIdentity_FullMethodName = "/ghostd.HostState/RepairIdentity"
	HostState_DHCPHandover_FullMethodName   = "/ghostd.HostState/DHCPHandover"
)

// HostStateClient is the client API for HostState service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostState is ghostd's whole RPC surface (README.md): the
// daemon does not decide policy, it executes a state Nornir already
// resolved. GetState answers with clean, diffable current state; Apply
// enacts a fully-resolved declarative target behind a dead-man's-switch;
// Confirm — called from a *fresh* connection, after independently
// reproving reachability — cancels that switch. No Confirm before the
// deadline restores the pre-apply snapshot.
type HostStateClient interface {
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*State, error)
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	Confirm(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error)
	// Registry reads are separate so ordinary firewall observations stay small.
	GetRegistry(ctx context.Context, in *RegistryRequest, opts ...grpc.CallOption) (*RegistryResponse, error)
	ImportLeases(ctx context.Context, in *RegistryDocument, opts ...grpc.CallOption) (*RegistryResponse, error)
	ReportHost(ctx context.Context, in *RegistryDocument, opts ...grpc.CallOption) (*RegistryResponse, error)
	RepairIdentity(ctx context.Context, in *RegistryDocument, opts ...grpc.CallOption) (*RegistryResponse, error)
	DHCPHandover(ctx context.Context, in *RegistryDocument, opts ...grpc.CallOption) (*RegistryResponse, error)
}

type hostStateClient struct {
	cc grpc.ClientConnInterface
}

func NewHostStateClient(cc grpc.ClientConnInterface) HostStateClient {
	return &hostStateClient{cc}
}

func (c *hostStateClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*State, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(State)
	err := c.cc.Invoke(ctx, HostState_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostStateClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, HostState_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostStateClient) Confirm(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmResponse)
	err := c.cc.Invoke(ctx, HostState_Confirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostStateClient) GetRegistry(ctx context.Context, in *RegistryRequest, opts ...grpc.CallOption) (*RegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryResponse)
	err := c.cc.Invoke(ctx, HostState_GetRegistry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostStateClient) ImportLeases(ctx context.Context, in *RegistryDocument, opts ...grpc.CallOption) (*RegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryResponse)
	err := c.cc.Invoke(ctx, HostState_ImportLeases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostStateClient) ReportHost(ctx context.Context, in *RegistryDocument, opts ...grpc.CallOption) (*RegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryResponse)
	err := c.cc.Invoke(ctx, HostState_ReportHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostStateClient) RepairIdentity(ctx context.Context, in *RegistryDocument, opts ...grpc.CallOption) (*RegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryResponse)
	err := c.cc.Invoke(ctx, HostState_RepairIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostStateClient) DHCPHandover(ctx context.Context, in *RegistryDocument, opts ...grpc.CallOption) (*RegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryResponse)
	err := c.cc.Invoke(ctx, HostState_DHCPHandover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostStateServer is the server API for HostState service.
// All implementations must embed UnimplementedHostStateServer
// for forward compatibility.
//
// HostState is ghostd's whole RPC surface (README.md): the
// daemon does not decide policy, it executes a state Nornir already
// resolved. GetState answers with clean, diffable current state; Apply
// enacts a fully-resolved declarative target behind a dead-man's-switch;
// Confirm — called from a *fresh* connection, after independently
// reproving reachability — cancels that switch. No Confirm before the
// deadline restores the pre-apply snapshot.
type HostStateServer interface {
	GetState(context.Context, *GetStateRequest) (*State, error)
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	Confirm(context.Context, *ConfirmRequest) (*ConfirmResponse, error)
	// Registry reads are separate so ordinary firewall observations stay small.
	GetRegistry(context.Context, *RegistryRequest) (*RegistryResponse, error)
	ImportLeases(context.Context, *RegistryDocument) (*RegistryResponse, error)
	ReportHost(context.Context, *RegistryDocument) (*RegistryResponse, error)
	RepairIdentity(context.Context, *RegistryDocument) (*RegistryResponse, error)
	DHCPHandover(context.Context, *RegistryDocument) (*RegistryResponse, error)
	mustEmbedUnimplementedHostStateServer()
}

// UnimplementedHostStateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostStateServer struct{}

func (UnimplementedHostStateServer) GetState(context.Context, *GetStateRequest) (*State, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedHostStateServer) Apply(context.Context, *ApplyRequest) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedHostStateServer) Confirm(context.Context, *ConfirmRequest) (*ConfirmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Confirm not implemented")
}
func (UnimplementedHostStateServer) GetRegistry(context.Context, *RegistryRequest) (*RegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRegistry not implemented")
}
func (UnimplementedHostStateServer) ImportLeases(context.Context, *RegistryDocument) (*RegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportLeases not implemented")
}
func (UnimplementedHostStateServer) ReportHost(context.Context, *RegistryDocument) (*RegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportHost not implemented")
}
func (UnimplementedHostStateServer) RepairIdentity(context.Context, *RegistryDocument) (*RegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RepairIdentity not implemented")
}
func (UnimplementedHostStateServer) DHCPHandover(context.Context, *RegistryDocument) (*RegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DHCPHandover not implemented")
}
func (UnimplementedHostStateServer) mustEmbedUnimplementedHostStateServer() {}
func (UnimplementedHostStateServer) testEmbeddedByValue()                   {}

// UnsafeHostStateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostStateServer will
// result in compilation errors.
type UnsafeHostStateServer interface {
	mustEmbedUnimplementedHostStateServer()
}

func RegisterHostStateServer(s grpc.ServiceRegistrar, srv HostStateServer) {
	// If the following call panics, it indicates UnimplementedHostStateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostState_ServiceDesc, srv)
}

func _HostState_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostStateServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostState_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostStateServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostState_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostStateServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostState_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostStateServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostState_Confirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostStateServer).Confirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostState_Confirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostStateServer).Confirm(ctx, req.(*ConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostState_GetRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostStateServer).GetRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostState_GetRegistry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostStateServer).GetRegistry(ctx, req.(*RegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostState_ImportLeases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryDocument)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostStateServer).ImportLeases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostState_ImportLeases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostStateServer).ImportLeases(ctx, req.(*RegistryDocument))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostState_ReportHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryDocument)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostStateServer).ReportHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostState_ReportHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostStateServer).ReportHost(ctx, req.(*RegistryDocument))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostState_RepairIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryDocument)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostStateServer).RepairIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostState_RepairIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostStateServer).RepairIdentity(ctx, req.(*RegistryDocument))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostState_DHCPHandover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryDocument)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostStateServer).DHCPHandover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostState_DHCPHandover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostStateServer).DHCPHandover(ctx, req.(*RegistryDocument))
	}
	return interceptor(ctx, in, info, handler)
}

// HostState_ServiceDesc is the grpc.ServiceDesc for HostState service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostState_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ghostd.HostState",
	HandlerType: (*HostStateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _HostState_GetState_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _HostState_Apply_Handler,
		},
		{
			MethodName: "Confirm",
			Handler:    _HostState_Confirm_Handler,
		},
		{
			MethodName: "GetRegistry",
			Handler:    _HostState_GetRegistry_Handler,
		},
		{
			MethodName: "ImportLeases",
			Handler:    _HostState_ImportLeases_Handler,
		},
		{
			MethodName: "ReportHost",
			Handler:    _HostState_ReportHost_Handler,
		},
		{
			MethodName: "RepairIdentity",
			Handler:    _HostState_RepairIdentity_Handler,
		},
		{
			MethodName: "DHCPHandover",
			Handler:    _HostState_DHCPHandover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ghoststate.proto",
}
