// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: ghoststate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	AtUnix        int64                  `protobuf:"varint,3,opt,name=at_unix,json=atUnix,proto3" json:"at_unix,omitempty"`
	AfterEvent    uint64                 `protobuf:"varint,4,opt,name=after_event,json=afterEvent,proto3" json:"after_event,omitempty"`
	EventLimit    uint32                 `protobuf:"varint,5,opt,name=event_limit,json=eventLimit,proto3" json:"event_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryRequest) Reset() {
	*x = RegistryRequest{}
	mi := &file_ghoststate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRequest) ProtoMessage() {}

func (x *RegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghoststate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRequest.ProtoReflect.Descriptor instead.
func (*RegistryRequest) Descriptor() ([]byte, []int) {
	return file_ghoststate_proto_rawDescGZIP(), []int{0}
}

func (x *RegistryRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *RegistryRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegistryRequest) GetAtUnix() int64 {
	if x != nil {
		return x.AtUnix
	}
	return 0
}

func (x *RegistryRequest) GetAfterEvent() uint64 {
	if x != nil {
		return x.AfterEvent
	}
	return 0
}

func (x *RegistryRequest) GetEventLimit() uint32 {
	if x != nil {
		return x.EventLimit
	}
	return 0
}

type RegistryDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryDocument) Reset() {
	*x = RegistryDocument{}
	mi := &file_ghoststate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryDocument) ProtoMessage() {}

func (x *RegistryDocument) ProtoReflect() protoreflect.Message {
	mi := &file_ghoststate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryDocument.ProtoReflect.Descriptor instead.
func (*RegistryDocument) Descriptor() ([]byte, []int) {
	return file_ghoststate_proto_rawDescGZIP(), []int{1}
}

func (x *RegistryDocument) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type RegistryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryResponse) Reset() {
	*x = RegistryResponse{}
	mi := &file_ghoststate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryResponse) ProtoMessage() {}

func (x *RegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ghoststate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryResponse.ProtoReflect.Descriptor instead.
func (*RegistryResponse) Descriptor() ([]byte, []int) {
	return file_ghoststate_proto_rawDescGZIP(), []int{2}
}

func (x *RegistryResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type GetStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional fixed read-only adoption evidence; ordinary state reads stay lightweight.
	IncludeAdoptionEvidence bool `protobuf:"varint,1,opt,name=include_adoption_evidence,json=includeAdoptionEvidence,proto3" json:"include_adoption_evidence,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_ghoststate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghoststate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_ghoststate_proto_rawDescGZIP(), []int{3}
}

func (x *GetStateRequest) GetIncludeAdoptionEvidence() bool {
	if x != nil {
		return x.IncludeAdoptionEvidence
	}
	return false
}

// State is deliberately a thin envelope around raw, structured JSON per
// domain rather than a typed nftables/netconfig schema in proto itself:
// each domain's real shape is still being designed (Phase 4/5), and the
// envelope is what lets GetState/Apply exist now without churning the
// wire format every time a domain's internals change.
type State struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `nft -j list ruleset` output, verbatim.
	NftRulesetJson string `protobuf:"bytes,1,opt,name=nft_ruleset_json,json=nftRulesetJson,proto3" json:"nft_ruleset_json,omitempty"`
	// The caller's own live-read shape for interface configuration (persisted
	// interfaces.d file bytes + `ip -j addr show` + /proc/sys/net/ipv4/ip_forward),
	// as JSON.
	NetconfigJson        string `protobuf:"bytes,2,opt,name=netconfig_json,json=netconfigJson,proto3" json:"netconfig_json,omitempty"`
	AdoptionEvidenceJson string `protobuf:"bytes,3,opt,name=adoption_evidence_json,json=adoptionEvidenceJson,proto3" json:"adoption_evidence_json,omitempty"`
	DhcpConfigJson       string `protobuf:"bytes,4,opt,name=dhcp_config_json,json=dhcpConfigJson,proto3" json:"dhcp_config_json,omitempty"`
	// The mdns-v1 domain's current advertised set, empty when the mdns
	// feature is not built in or nothing is configured. See
	// internal/mdns.Config for the shape.
	MdnsConfigJson string `protobuf:"bytes,5,opt,name=mdns_config_json,json=mdnsConfigJson,proto3" json:"mdns_config_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_ghoststate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_ghoststate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_ghoststate_proto_rawDescGZIP(), []int{4}
}

func (x *State) GetNftRulesetJson() string {
	if x != nil {
		return x.NftRulesetJson
	}
	return ""
}

func (x *State) GetNetconfigJson() string {
	if x != nil {
		return x.NetconfigJson
	}
	return ""
}

func (x *State) GetAdoptionEvidenceJson() string {
	if x != nil {
		return x.AdoptionEvidenceJson
	}
	return ""
}

func (x *State) GetDhcpConfigJson() string {
	if x != nil {
		return x.DhcpConfigJson
	}
	return ""
}

func (x *State) GetMdnsConfigJson() string {
	if x != nil {
		return x.MdnsConfigJson
	}
	return ""
}

type ApplyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The fully-resolved declarative target the caller computed — not a diff.
	DesiredStateJson string `protobuf:"bytes,1,opt,name=desired_state_json,json=desiredStateJson,proto3" json:"desired_state_json,omitempty"`
	// How long the dead-man's-switch waits for Confirm before reverting to
	// the pre-apply snapshot. Required; the caller does not get to apply
	// with no revert path.
	DeadManSwitchSeconds int32 `protobuf:"varint,2,opt,name=dead_man_switch_seconds,json=deadManSwitchSeconds,proto3" json:"dead_man_switch_seconds,omitempty"`
	// Which domain desired_state_json is for: "firewall" or "netconfig".
	// Required — the two domains' desired_state_json shapes are incompatible,
	// and routing one to the wrong renderer on a guess is not a survivable
	// mistake to auto-detect.
	Domain        string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_ghoststate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghoststate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_ghoststate_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyRequest) GetDesiredStateJson() string {
	if x != nil {
		return x.DesiredStateJson
	}
	return ""
}

func (x *ApplyRequest) GetDeadManSwitchSeconds() int32 {
	if x != nil {
		return x.DeadManSwitchSeconds
	}
	return 0
}

func (x *ApplyRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_ghoststate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ghoststate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_ghoststate_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type ConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_ghoststate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghoststate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_ghoststate_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type ConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmResponse) Reset() {
	*x = ConfirmResponse{}
	mi := &file_ghoststate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmResponse) ProtoMessage() {}

func (x *ConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ghoststate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmResponse.ProtoReflect.Descriptor instead.
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return file_ghoststate_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_ghoststate_proto protoreflect.FileDescriptor

const file_ghoststate_proto_rawDesc = "" +
	"\n" +
	"\x10ghoststate.proto\x12\x06ghostd\"\x9c\x01\n" +
	"\x0fRegistryRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x17\n" +
	"\aat_unix\x18\x03 \x01(\x03R\x06atUnix\x12\x1f\n" +
	"\vafter_event\x18\x04 \x01(\x04R\n" +
	"afterEvent\x12\x1f\n" +
	"\vevent_limit\x18\x05 \x01(\rR\n" +
	"eventLimit\"&\n" +
	"\x10RegistryDocument\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"&\n" +
	"\x10RegistryResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"M\n" +
	"\x0fGetStateRequest\x12:\n" +
	"\x19include_adoption_evidence\x18\x01 \x01(\bR\x17includeAdoptionEvidence\"\xe2\x01\n" +
	"\x05State\x12(\n" +
	"\x10nft_ruleset_json\x18\x01 \x01(\tR\x0enftRulesetJson\x12%\n" +
	"\x0enetconfig_json\x18\x02 \x01(\tR\rnetconfigJson\x124\n" +
	"\x16adoption_evidence_json\x18\x03 \x01(\tR\x14adoptionEvidenceJson\x12(\n" +
	"\x10dhcp_config_json\x18\x04 \x01(\tR\x0edhcpConfigJson\x12(\n" +
	"\x10mdns_config_json\x18\x05 \x01(\tR\x0emdnsConfigJson\"\x8b\x01\n" +
	"\fApplyRequest\x12,\n" +
	"\x12desired_state_json\x18\x01 \x01(\tR\x10desiredStateJson\x125\n" +
	"\x17dead_man_switch_seconds\x18\x02 \x01(\x05R\x14deadManSwitchSeconds\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\"*\n" +
	"\rApplyResponse\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"+\n" +
	"\x0eConfirmRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"!\n" +
	"\x0fConfirmResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\x92\x05\n" +
	"\tHostState\x122\n" +
	"\bGetState\x12\x17.ghostd.GetStateRequest\x1a\r.ghostd.State\x124\n" +
	"\x05Apply\x12\x14.ghostd.ApplyRequest\x1a\x15.ghostd.ApplyResponse\x12:\n" +
	"\aConfirm\x12\x16.ghostd.ConfirmRequest\x1a\x17.ghostd.ConfirmResponse\x12@\n" +
	"\vGetRegistry\x12\x17.ghostd.RegistryRequest\x1a\x18.ghostd.RegistryResponse\x12B\n" +
	"\fImportLeases\x12\x18.ghostd.RegistryDocument\x1a\x18.ghostd.RegistryResponse\x12@\n" +
	"\n" +
	"ReportHost\x12\x18.ghostd.RegistryDocument\x1a\x18.ghostd.RegistryResponse\x12D\n" +
	"\x0eRepairIdentity\x12\x18.ghostd.RegistryDocument\x1a\x18.ghostd.RegistryResponse\x12B\n" +
	"\fDHCPHandover\x12\x18.ghostd.RegistryDocument\x1a\x18.ghostd.RegistryResponse\x12H\n" +
	"\x12ImportObservations\x12\x18.ghostd.RegistryDocument\x1a\x18.ghostd.RegistryResponse\x12C\n" +
	"\x0eGetSuggestions\x12\x17.ghostd.RegistryRequest\x1a\x18.ghostd.RegistryResponseB\x1fZ\x1dgithub.com/xaiki/ghostd/protob\x06proto3"

var (
	file_ghoststate_proto_rawDescOnce sync.Once
	file_ghoststate_proto_rawDescData []byte
)

func file_ghoststate_proto_rawDescGZIP() []byte {
	file_ghoststate_proto_rawDescOnce.Do(func() {
		file_ghoststate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ghoststate_proto_rawDesc), len(file_ghoststate_proto_rawDesc)))
	})
	return file_ghoststate_proto_rawDescData
}

var file_ghoststate_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ghoststate_proto_goTypes = []any{
	(*RegistryRequest)(nil),  // 0: ghostd.RegistryRequest
	(*RegistryDocument)(nil), // 1: ghostd.RegistryDocument
	(*RegistryResponse)(nil), // 2: ghostd.RegistryResponse
	(*GetStateRequest)(nil),  // 3: ghostd.GetStateRequest
	(*State)(nil),            // 4: ghostd.State
	(*ApplyRequest)(nil),     // 5: ghostd.ApplyRequest
	(*ApplyResponse)(nil),    // 6: ghostd.ApplyResponse
	(*ConfirmRequest)(nil),   // 7: ghostd.ConfirmRequest
	(*ConfirmResponse)(nil),  // 8: ghostd.ConfirmResponse
}
var file_ghoststate_proto_depIdxs = []int32{
	3,  // 0: ghostd.HostState.GetState:input_type -> ghostd.GetStateRequest
	5,  // 1: ghostd.HostState.Apply:input_type -> ghostd.ApplyRequest
	7,  // 2: ghostd.HostState.Confirm:input_type -> ghostd.ConfirmRequest
	0,  // 3: ghostd.HostState.GetRegistry:input_type -> ghostd.RegistryRequest
	1,  // 4: ghostd.HostState.ImportLeases:input_type -> ghostd.RegistryDocument
	1,  // 5: ghostd.HostState.ReportHost:input_type -> ghostd.RegistryDocument
	1,  // 6: ghostd.HostState.RepairIdentity:input_type -> ghostd.RegistryDocument
	1,  // 7: ghostd.HostState.DHCPHandover:input_type -> ghostd.RegistryDocument
	1,  // 8: ghostd.HostState.ImportObservations:input_type -> ghostd.RegistryDocument
	0,  // 9: ghostd.HostState.GetSuggestions:input_type -> ghostd.RegistryRequest
	4,  // 10: ghostd.HostState.GetState:output_type -> ghostd.State
	6,  // 11: ghostd.HostState.Apply:output_type -> ghostd.ApplyResponse
	8,  // 12: ghostd.HostState.Confirm:output_type -> ghostd.ConfirmResponse
	2,  // 13: ghostd.HostState.GetRegistry:output_type -> ghostd.RegistryResponse
	2,  // 14: ghostd.HostState.ImportLeases:output_type -> ghostd.RegistryResponse
	2,  // 15: ghostd.HostState.ReportHost:output_type -> ghostd.RegistryResponse
	2,  // 16: ghostd.HostState.RepairIdentity:output_type -> ghostd.RegistryResponse
	2,  // 17: ghostd.HostState.DHCPHandover:output_type -> ghostd.RegistryResponse
	2,  // 18: ghostd.HostState.ImportObservations:output_type -> ghostd.RegistryResponse
	2,  // 19: ghostd.HostState.GetSuggestions:output_type -> ghostd.RegistryResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_ghoststate_proto_init() }
func file_ghoststate_proto_init() {
	if File_ghoststate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ghoststate_proto_rawDesc), len(file_ghoststate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ghoststate_proto_goTypes,
		DependencyIndexes: file_ghoststate_proto_depIdxs,
		MessageInfos:      file_ghoststate_proto_msgTypes,
	}.Build()
	File_ghoststate_proto = out.File
	file_ghoststate_proto_goTypes = nil
	file_ghoststate_proto_depIdxs = nil
}
